# Generated by Django 4.2.5 on 2023-09-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
