# Generated by Django 4.2.5 on 2023-09-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposts',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
